Replace FuzzyDateTime with FuzzyNaiveDateTime
Because I got this error:

    ValueError: MySQL backend does not support timezone-aware datetimes when USE_TZ is False.