Fix really strange bug about conflicting models
The bug:

    Failure: RuntimeError (Conflicting 'c' models in application 'nose': <class 'manoseimas.compatibility_test.admin.TestGroup'> and <class 'nose.util.C'>.) ... ERROR

    ======================================================================
    ERROR: Failure: RuntimeError (Conflicting 'c' models in application 'nose': <class 'manoseimas.compatibility_test.admin.TestGroup'> and <class 'nose.util.C'>.)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
    eggs/nose-1.3.7-py2.7.egg/nose/loader.py|523| in makeTest
        return self._makeTest(obj, parent)
    eggs/nose-1.3.7-py2.7.egg/nose/loader.py|568| in _makeTest
        obj = transplant_class(obj, parent.__name__)
    eggs/nose-1.3.7-py2.7.egg/nose/util.py|642| in transplant_class
        class C(cls):
    eggs/Django-1.8.5-py2.7.egg/django/db/models/base.py|309| in __new__
        new_class._meta.apps.register_model(new_class._meta.app_label, new_class)
    eggs/Django-1.8.5-py2.7.egg/django/apps/registry.py|221| in register_model
        (model_name, app_label, app_models[model_name], model))
    RuntimeError: Conflicting 'c' models in application 'nose': <class 'manoseimas.compatibility_test.admin.TestGroup'> and <class 'nose.util.C'>.

Have no idea what is going on here, but it seems related to this bug report:

https://code.djangoproject.com/ticket/22280

To reproduce this bug it is enough to add this line:

    from manoseimas.compatibility_test.models import TestGroup

to `manoseimas/compatibility_test/admin.py`, some how it conflicts with `nose`,
but I'm not sure what `nose` has to do with Django apps and models?

Anyway changing the way how `TestGroup` is imported fixes the bug.